services:
  - type: web
    name: frontrow-backend
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    env:
      - key: NODE_ENV
        value: production 